// Portfolio demo: answers /api/* from fixtures generated by running the real FastAPI
// services over fictional sheet data. No network, no company data.
(function () {
  var F = window.CEO_FIXTURES || {}, real = window.fetch.bind(window);
  window.fetch = function (input, opts) {
    var url = new URL(typeof input === 'string' ? input : input.url, location.href);
    var m = url.pathname.match(/\/api\/([a-z-]+)$/);
    if (!m) return real(input, opts);
    var key = m[1], q = url.searchParams;
    if (key === 'stock-snapshots') key += '-' + (q.get('type') === 'rm' ? 'rm' : 'fg');
    if (key === 'pipeline' && q.get('month') && F['pipeline-' + q.get('month')]) key = 'pipeline-' + q.get('month');
    var body = F[key] || { ok: true };
    return new Promise(function (res) { setTimeout(function () {
      res(new Response(JSON.stringify(body), { status: 200, headers: { 'Content-Type': 'application/json' } }));
    }, 160); });
  };
})();
